############################################################
# Justfile docs - https://just.systems/man/en/
# Justfile cheatsheet https://cheatography.com/linux-china/cheat-sheets/justfile/
############################################################

############################################################
# Justfile settings (https://just.systems/man/en/chapter_26.html)
# - 'shell' : Set the command used to invoke recipes and evaluate backticks.
############################################################
set shell := ["bash", "-cu"]

############################################################
# Justfile Env-vars (https://just.systems/man/en/chapter_31.html#environment-variables)
############################################################
set dotenv-filename := ".env"
# Define the environment file based on the parameter
set dotenv_load := true
# set dotenv-filename := ".env.local"

# Justfile Env-vars (https://just.systems/man/en/chapter_31.html#environment-variables)
project_root_justfile_dir := justfile_directory()
openapi_root := project_root_justfile_dir / "openapi"
salesforce-host := env_var('SALESFORCE_PATTER_AI_ORG_HOST')
salesforce-user := env_var('SALESFORCE_PATTER_AI_ORG_USER')
salesforce-password := env_var('SALESFORCE_PATTER_AI_ORG_PASS')
salesforce-token := env_var('SALESFORCE_PATTER_AI_ORG_SECURITY_TOKEN')

############################################################
# Common Utils
############################################################

help:
    @echo "###################################"
    @echo "salesforce config env-vars"
    @echo "###################################"
    @echo ""
    @echo ""
    @just --list --unsorted

run-recipe:
    @just --choose

format-justfile-in-place:
    @just --fmt --unstable

############################################################
# Common Utils
############################################################

# Start FastAPI server and database
start-backend: codegen-all
    docker compose -f {{project_root_justfile_dir}}/docker-compose.yml up

# Run all unit tests
api-tests: start-backend-detached
    @echo "TODO: Running API tests"
